### ISSUE TITLE
*path matching breaks delayed_job_admin route

### ISSUE THREAD

**Issue by randy-girard** [trevorturk/delayed_job_admin#1]
If you add something like

match '*path'         => "dashboard#not_recognized"

to the bottom of your routes file, it will take precedence over the delayed_job_admin routes file, essentially rendering it inaccessible.

**Comment by trevorturk** [comment]
Hmm... I'm not sure what to do about that. I suppose you could put the route in your routes file manually instead of letting the gem do it...?

**Comment by randy-girard** [comment]
Yea..I wasn't sure if there was a way to make it load first before the application specific ones load.

**Comment by trevorturk** [comment]
I dunno - I'm new to Rails 3 engines. If you want to take the time to try and figure it out, please do. I'd definitely take a pull request.
