### ISSUE TITLE
This is a bad design, because I have over 3 million jobs.

### ISSUE THREAD

**Issue by huacnlee** [trevorturk/delayed_job_admin#2]
Delayed::Job.all ... Oh NO! 
Why does not make a pagination for it?

**Comment by trevorturk** [comment]
Why don't you submit a pull request instead of leaving rude comments
like this? This is open source - if you dont like it - fix it!

On Saturday, March 12, 2011, huacnlee
reply@reply.github.com
wrote:

> Delayed::Job.all ... Oh NO!
> Why does not make a pagination for it?
> 
> https://github.com/trevorturk/delayed_job_admin/issues/2
