### ISSUE TITLE
Doesn't show up in my rails app

### ISSUE THREAD

**Issue by retorquere** [trevorturk/delayed_job_admin#4]
I've installed the gem and modified my application_controller, but the admin interface doesn't show up. I'm on rails 3.2

**Comment by trevorturk** [comment]
I'm sorry, but I'm not doing support for this since I'm not using it anymore. Good luck finding a solution, though!

**Comment by andyw8** [comment]
Works for me in Rails 3.2.9. Does the route show up when you run `rake routes`?
